import { Metadata } from "next";
import Head from "next/head";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import TopBar from "./components/Topbar";
import Header from "./components/Header";
import BackToTopBtn from "./components/BackToTopBtn";
import Footer from "./section/Footer";

// Import global styles
import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "glightbox/dist/css/glightbox.min.css";

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair-display',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Restaurant Hubert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN6jIeHz"
          crossOrigin="anonymous"
          defer
        ></script>
      </Head>
      <body className={`${playfair.variable}`}>
        <TopBar />
        <Header />
        {children}
        <Footer />
        <BackToTopBtn />
      </body>
    </html>
  );
}
